### ISSUE TITLE
[FEAT] 질문/댓글 비공개 설정 로직 생성

### ISSUE THREAD

**Issue by her0807** [SKHUED-IN/skhuedin#107]
## 목적
>  question에  status 필드만 있고, 상태가 업데이트 되는 로직이 아직 없다. 
프론트에 질문/댓글들을 불러오고, 질문, 댓글 상태가 변경 가능하도록 로직을 생성한다.

## 참고사항

**Comment by hyeonic** [comment]
question의 경우 updateQuestion을 활용하여 status의 값을 변경할 수 있어요! 추가적으로 고려해야 할 점은 comment인데, 각각의 comment의 상태를 변경하게 하기 위해서는 결국 status가 필요할 것으로 예상됩니다..
