### ISSUE TITLE
[FEAT] 엔티티 수정

### ISSUE THREAD

**Issue by her0807** [SKHUED-IN/skhuedin#18]
## 목적
> 바뀐 기능에 맞춰 디비를 수정함. 따라서 수정된 디비에 맞춰 엔티티 수정이 필요
## 작업 상세 내용
- [ ] [클래스 다이어그램] 에 맞춰서 엔티티 수정하기

## 참고사항

![image](https://user-images.githubusercontent.com/26570275/113685006-c4a6ec00-9700-11eb-8c5b-df39f62cdddf.png)

**Comment by hyeonic** [comment]
Post에 yearMonth 필드는 필요 없을 것 같아요! 이전에 있던 roadmap 부분 수정을 누락한 것 같네요. 또한 post에 대한 title이 필요할 것 같아서 코드에 추가하였습니다. 후에 Class diagram에도 반영할게요.

**Comment by hyeonic** [comment]
또한 Comment에 양방향 셀프조인을 위하여 List<Comment> children를 추가하였습니다.
